
services:
  - type: web
    name: tablegen-backend
    env: node
    rootDir: backend
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 10000
      - key: BASE_URL
        value: https://your-backend.onrender.com
  - type: static
    name: tablegen-frontend
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_BASE
        value: https://your-backend.onrender.com
