// backend/routes/pdf.js
import PDFDocument from "pdfkit";
import express from "express";

const router = express.Router();

/**
 * POST /v1/api/pdf
 * body: { title?: string, body?: string }
 * 返回 application/pdf
 */
router.post("/pdf", async (req, res) => {
  try {
    const { title = "报价单", body = "这是由后端生成的 PDF 示例。" } = req.body || {};

    const doc = new PDFDocument({ size: "A4", margin: 50 });

    res.setHeader("Content-Type", "application/pdf");
    res.setHeader("Content-Disposition", 'inline; filename="quote.pdf"');

    doc.pipe(res);

    doc.fontSize(20).text(title, { align: "center" }).moveDown(1.2);
    doc.fontSize(12).text(body, { align: "left" });
    doc.moveDown(2);
    doc.fontSize(10).fillColor("#666").text("Generated by Yunivera MVP3", { align: "right" });

    doc.end();
  } catch (err) {
    console.error("PDF error:", err);
    res.status(500).json({ ok: false, error: String(err) });
  }
});

export default router;
